import { Metadata } from 'next';

import { baseOpenGraph } from '@/constants/metadata';
import { Markdown } from '@/components/Markdown';

import { getAllPosts } from '../getAllPosts';
import { getPostBySlug } from '../getPost';
import { getPostText } from '../getPostText';
import { slugToFilename } from '../postFilename';

import styles from './page.module.css';

interface BlogPostProps {
  params: {
    slug: string[];
    meta: Record<string, string>;
  };
}

const BlogPost = async ({ params }: BlogPostProps) => {
  const { content, meta } = await getPostBySlug(params.slug);

  const dateFormat: Intl.DateTimeFormatOptions = {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  } as const;

  const date = new Date(meta.date)
    .toLocaleDateString('en-GB', dateFormat)
    .replace(',', '');

  return (
    <article className={styles.article}>
      <div className={styles.meta}>
        <h2 className={styles.title}>{meta.title}</h2>
        <span className={styles.date}>{date}</span>
      </div>

      <div>
        <Markdown>{content}</Markdown>
      </div>
    </article>
  );
};

export default BlogPost;

export const generateStaticParams = async () => {
  return getAllPosts();
};

// Don't allow routes that aren't generated by generateStaticParams
export const dynamicParams = false;

export const generateMetadata = async ({
  params,
}: BlogPostProps): Promise<Metadata> => {
  const { meta } = await getPostBySlug(params.slug);

  const filename = `./app/blog/posts/${slugToFilename(params.slug)}`;
  const postText = getPostText(filename);
  const firstParagraph = postText.split('\n\n')[0];
  const excerpt = firstParagraph
    .split(' ')
    .slice(0, 50)
    .join(' ')
    .replaceAll('\n', ' ');

  const { title, description = excerpt, date } = meta;

  return {
    title,
    description,
    openGraph: {
      ...baseOpenGraph,
      type: 'article',
      title: { absolute: title },
      description,
      publishedTime: date,
      authors: ['Liv Asch'],
    },
  };
};
