import { Metadata } from 'next';

import { getAllPosts } from '../getAllPosts';
import { getPostBySlug } from '../getPost';

import styles from './page.module.css';

interface BlogPostProps {
  params: {
    slug: string[];
    meta: Record<string, string>;
  };
}

const BlogPost = async ({ params }: BlogPostProps) => {
  const { Content, meta } = await getPostBySlug(params.slug);

  const dateFormat: Intl.DateTimeFormatOptions = {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  } as const;

  const date = new Date(meta.date)
    .toLocaleDateString('en-GB', dateFormat)
    .replace(',', '');

  return (
    <article className={styles.article}>
      <div className={styles.meta}>
        <h2 className={styles.title}>{meta.title}</h2>
        <span className={styles.date}>{date}</span>
      </div>

      <div>
        <Content />
      </div>
    </article>
  );
};

export default BlogPost;

export const generateStaticParams = async () => {
  return getAllPosts();
};

// Don't allow routes that aren't generated by generateStaticParams
export const dynamicParams = false;

export const generateMetadata = async ({
  params,
}: BlogPostProps): Promise<Metadata> => {
  const { meta } = await getPostBySlug(params.slug);

  const { title, description, date } = meta;

  return {
    title,
    description,
    openGraph: {
      type: 'article',
      title: { absolute: title },
      publishedTime: date,
      authors: ['Liv Asch'],
    },
  };
};
