import { Metadata } from 'next';

import { baseOpenGraph } from '@/utils/metadata';
import { Markdown } from '@/components/Markdown';

import { getAllPosts } from '../getAllPosts';
import { getPostBySlug } from '../getPost';

import './postElements.css';
import styles from './page.module.css';
import removeMarkdown from 'remove-markdown';

interface BlogPostProps {
  params: {
    slug: string[];
    meta: Record<string, string>;
  };
}

const BlogPost = ({ params }: BlogPostProps) => {
  const { content, meta } = getPostBySlug(params.slug);

  const dateFormat: Intl.DateTimeFormatOptions = {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  } as const;

  const date = new Date(meta.date)
    .toLocaleDateString('en-GB', dateFormat)
    .replace(',', '');

  return (
    <article className={styles.article}>
      <div className={styles.meta}>
        <h2 className={styles.title}>{meta.title}</h2>
        <span className={styles.date}>{date}</span>
      </div>

      <div>
        <Markdown>{content}</Markdown>
      </div>
    </article>
  );
};

export default BlogPost;

export const generateStaticParams = async () => {
  return getAllPosts();
};

// Don't allow routes that aren't generated by generateStaticParams
export const dynamicParams = false;

export const generateMetadata = ({ params }: BlogPostProps): Metadata => {
  const { content, meta } = getPostBySlug(params.slug);

  const rawContent = removeMarkdown(content);
  const firstParagraph = rawContent.split('\n\n')[0];
  const excerpt = firstParagraph
    .split(' ')
    .slice(0, 50)
    .join(' ')
    .replaceAll('\n', ' ')
    .trim();

  const { title, description = excerpt, date, hero } = meta;

  const images = hero ? { images: [hero] } : {};

  return {
    title,
    description,
    openGraph: {
      ...baseOpenGraph,
      type: 'article',
      title: { absolute: title },
      description,
      publishedTime: date,
      authors: ['Liv Flowers'],
      ...images,
    },
    twitter: {
      card: hero ? 'summary_large_image' : 'summary',
      title,
      description,
      images: hero ? [hero] : undefined,
    },
  };
};
